# Write only your current Stage 04 challenge attempt below this line.
header="[INTEGER CAPSTONE]"
text=input("First integer: ")
first_number=int(text)
text=input("Current integer: ")
number=int(text)
print(number)
print(header)
print(first_number)
print("")
text=input("Next integer: ")
number=int(text)
print(header)
print(number)
print(first_number)
